// Generated file - DO NOT EDIT 

export default {
	"country_name": "country_code",
	"Andorra": "ad",
	"United Arab Emirates": "ae",
	"Afghanistan": "af",
	"Antigua and Barbuda": "ag",
	"Albania": "al",
	"Armenia": "am",
	"Angola": "ao",
	"Argentina": "ar",
	"Austria": "at",
	"Australia": "au",
	"Azerbaijan": "az",
	"Bosnia and Herzegovina": "ba",
	"Barbados": "bb",
	"Bangladesh": "bd",
	"Belgium": "be",
	"Burkina Faso": "bf",
	"Bulgaria": "bg",
	"Bahrain": "bh",
	"Burundi": "bi",
	"Benin": "bj",
	"Brunei Darussalam": "bn",
	"Bolivia (Plurinational State Of)": "bo",
	"Brazil": "br",
	"Bahamas": "bs",
	"Bhutan": "bt",
	"Botswana": "bw",
	"Belarus": "by",
	"Belize": "bz",
	"Canada": "ca",
	"Congo (the Democratic Republic of the)": "cd",
	"Central African Republic": "cf",
	"Congo": "cg",
	"Switzerland": "ch",
	"Cote d’Ivoire": "ci",
	"Chile": "cl",
	"Cameroon": "cm",
	"China": "cn",
	"Colombia": "co",
	"Costa Rica": "cr",
	"Cuba": "cu",
	"Cabo Verde": "cv",
	"Cyprus": "cy",
	"Czechia": "cz",
	"Germany": "de",
	"Djibouti": "dj",
	"Denmark": "dk",
	"Dominica": "dm",
	"Dominican Republic": "do",
	"Algeria": "dz",
	"Ecuador": "ec",
	"Estonia": "ee",
	"Egypt": "eg",
	"Eritrea": "er",
	"Spain": "es",
	"Ethiopia": "et",
	"Finland": "fi",
	"Fiji": "fj",
	"Micronesia (Federated States of)": "fm",
	"France": "fr",
	"Gabon": "ga",
	"United Kingdom of Great Britain and Northern Ireland": "gb",
	"Grenada": "gd",
	"Georgia": "ge",
	"French Guiana": "gf",
	"Ghana": "gh",
	"Gambia (the)": "gm",
	"Guinea": "gn",
	"Equatorial Guinea": "gq",
	"Greece": "gr",
	"Guatemala": "gt",
	"Guinea-Bissau": "gw",
	"Guyana": "gy",
	"Honduras": "hn",
	"Croatia": "hr",
	"Haiti": "ht",
	"Hungary": "hu",
	"Indonesia": "id",
	"Ireland": "ie",
	"Israel": "il",
	"India": "in",
	"Iraq": "iq",
	"Iran (Islamic Republic of)": "ir",
	"Iceland": "is",
	"Italy": "it",
	"Jamaica": "jm",
	"Jordan": "jo",
	"Japan": "jp",
	"Kenya": "ke",
	"Kyrgyzstan": "kg",
	"Cambodia": "kh",
	"Kiribati": "ki",
	"Comoros": "km",
	"Saint Kitts and Nevis": "kn",
	"Korea (Democratic People's Republic of)": "kp",
	"Korea (the Republic of)": "kr",
	"Kuwait": "kw",
	"Kazakhstan": "kz",
	"Lao People's Democratic Republic": "la",
	"Lebanon": "lb",
	"Saint Lucia": "lc",
	"Liechtenstein": "li",
	"Sri Lanka": "lk",
	"Liberia": "lr",
	"Lesotho": "ls",
	"Lithuania": "lt",
	"Luxembourg": "lu",
	"Latvia": "lv",
	"Libya": "ly",
	"Morocco": "ma",
	"Monaco": "mc",
	"Moldova (the Republic of)": "md",
	"Montenegro": "me",
	"Madagascar": "mg",
	"Marshall Islands": "mh",
	"North Macedonia": "mk",
	"Mali": "ml",
	"Myanmar": "mm",
	"Mongolia": "mn",
	"Mauritania": "mr",
	"Malta": "mt",
	"Mauritius": "mu",
	"Maldives": "mv",
	"Malawi": "mw",
	"Mexico": "mx",
	"Malaysia": "my",
	"Mozambique": "mz",
	"Namibia": "na",
	"Niger": "ne",
	"Nigeria": "ng",
	"Nicaragua": "ni",
	"Netherlands": "nl",
	"Norway": "no",
	"Nepal": "np",
	"Nauru": "nr",
	"New Zealand": "nz",
	"Oman": "om",
	"Panama": "pa",
	"Peru": "pe",
	"Papua New Guinea": "pg",
	"Philippines": "ph",
	"Pakistan": "pk",
	"Poland": "pl",
	"Portugal": "pt",
	"Palau": "pw",
	"Paraguay": "py",
	"Qatar": "qa",
	"Romania": "ro",
	"Serbia": "rs",
	"Russian Federation": "ru",
	"Rwanda": "rw",
	"Saudi Arabia": "sa",
	"Solomon Islands": "sb",
	"Seychelles": "sc",
	"Sudan": "sd",
	"Sweden": "se",
	"Singapore": "sg",
	"Slovenia": "si",
	"Slovakia": "sk",
	"Sierra Leone": "sl",
	"San Marino": "sm",
	"Senegal": "sn",
	"Somalia": "so",
	"Suriname": "sr",
	"South Sudan": "ss",
	"Sao Tome and Principe": "st",
	"El Salvador": "sv",
	"Syrian Arab Republic": "sy",
	"Eswatini": "sz",
	"Chad": "td",
	"Togo": "tg",
	"Thailand": "th",
	"Tajikistan": "tj",
	"Timor-Leste": "tl",
	"Turkmenistan": "tm",
	"Tunisia": "tn",
	"Tonga": "to",
	"Turkey": "tr",
	"Trinidad and Tobago": "tt",
	"Tuvalu": "tv",
	"Tanzania (the United Republic of)": "tz",
	"Ukraine": "ua",
	"Uganda": "ug",
	"United States of America": "us",
	"Uruguay": "uy",
	"Uzbekistan": "uz",
	"Saint Vincent and the Grenadines": "vc",
	"Venezuela (Bolivarian Republic of)": "ve",
	"Viet Nam": "vn",
	"Vanuatu": "vu",
	"Samoa": "ws",
	"Yemen": "ye",
	"South Africa": "za",
	"Zambia": "zm",
	"Zimbabwe": "zw",
};