export default {
	"ad": ["es", "fr"],
	"ae": ["om", "sa"],
	"af": ["pk", "uz", "tm", "cn", "tj", "ir"],
	"ag": [""],
	"al": ["me", "mk", "gr", "rs"],
	"am": ["az", "ge", "tr", "ir"],
	"ao": ["zm", "na", "cd", "cg"],
	"ar": ["uy", "cl", "py", "bo", "br"],
	"at": ["it", "ch", "li", "si", "sk", "hu", "cz", "de"],
	"au": [""],
	"az": ["ge", "tr", "ru", "am", "ir"],
	"ba": ["me", "rs", "hr"],
	"bb": [""],
	"bd": ["in", "mm"],
	"be": ["nl", "lu", "de", "fr"],
	"bf": ["ml", "ne", "tg", "bj", "gh", "ci"],
	"bg": ["rs", "tr", "gr", "mk", "ro"],
	"bh": [""],
	"bi": ["rw", "cd", "tz"],
	"bj": ["tg", "ng", "ne", "bf"],
	"bn": ["my"],
	"bo": ["pe", "ar", "cl", "py", "br"],
	"br": ["pe", "gy", "co", "uy", "ar", "ve", "py", "bo", "sr"],
	"bs": [""],
	"bt": ["in", "cn"],
	"bw": ["zw", "zm", "na", "za"],
	"by": ["pl", "lt", "ru", "ua", "lv"],
	"bz": ["mx", "gt"],
	"ca": ["us"],
	"cd": ["bi", "zm", "cg", "ao", "tz", "rw", "ss", "cf", "ug"],
	"cf": ["cg", "td", "cm", "ss", "sd", "cd"],
	"cg": ["cd", "ao", "cm", "cf", "ga"],
	"ch": ["it", "fr", "li", "at", "de"],
	"ci": ["ml", "lr", "bf", "gh", "gn"],
	"cl": ["ar", "pe", "bo"],
	"cm": ["cg", "td", "ng", "cf", "gq", "ga"],
	"cn": ["pk", "mm", "kp", "af", "in", "mn", "ru", "kg", "bt", "la", "np", "tj", "vn", "kz"],
	"co": ["pa", "pe", "ec", "ve", "br"],
	"cr": ["pa", "ni"],
	"cu": [""],
	"cv": [""],
	"cy": [""],
	"cz": ["pl", "at", "sk", "de"],
	"de": ["pl", "lu", "ch", "fr", "nl", "at", "be", "cz", "dk"],
	"dj": ["so", "et", "er"],
	"dk": ["de"],
	"dm": [""],
	"do": ["ht"],
	"dz": ["ml", "mr", "ne", "ly", "ma", "tn"],
	"ec": ["pe", "co"],
	"ee": ["ru", "lv"],
	"eg": ["ly", "sd", "il"],
	"er": ["et", "sd", "dj"],
	"es": ["pt", "ma", "fr", "ad"],
	"et": ["dj", "ke", "ss", "so", "sd", "er"],
	"fi": ["no", "ru", "se"],
	"fj": [""],
	"fm": [""],
	"fr": ["it", "lu", "mc", "ch", "ad", "be", "de", "es"],
	"ga": ["gq", "cm", "cg"],
	"gb": ["ie"],
	"gd": [""],
	"ge": ["am", "az", "ru", "tr"],
	"gh": ["tg", "bf", "ci"],
	"gm": ["sn"],
	"gn": ["ml", "lr", "sn", "gw", "sl", "ci"],
	"gq": ["cm", "ga"],
	"gr": ["al", "mk", "bg", "tr"],
	"gt": ["hn", "mx", "sv", "bz"],
	"gw": ["sn", "gn"],
	"gy": ["sr", "ve", "br"],
	"hn": ["ni", "sv", "gt"],
	"hr": ["me", "rs", "si", "ba", "hu"],
	"ht": ["do"],
	"hu": ["rs", "si", "sk", "at", "hr", "ua", "ro"],
	"id": ["pg", "tl", "my"],
	"ie": ["gb"],
	"il": ["jo", "lb", "eg", "sy"],
	"in": ["pk", "mm", "bd", "np", "bt", "cn"],
	"iq": ["tr", "jo", "kw", "sa", "sy", "ir"],
	"ir": ["pk", "af", "tr", "iq", "tm", "am", "az"],
	"is": [""],
	"it": ["ch", "fr", "si", "sm", "at"],
	"jm": [""],
	"jo": ["iq", "sa", "il", "sy"],
	"jp": [""],
	"ke": ["tz", "et", "ss", "so", "ug"],
	"kg": ["tj", "uz", "kz", "cn"],
	"kh": ["th", "vn", "la"],
	"ki": [""],
	"km": [""],
	"kn": [""],
	"kp": ["ru", "kr", "cn"],
	"kr": ["kp"],
	"kw": ["iq", "sa"],
	"kz": ["ru", "kg", "uz", "tm", "cn"],
	"la": ["mm", "kh", "cn", "vn", "th"],
	"lb": ["il", "sy"],
	"lc": [""],
	"li": ["at", "ch"],
	"lk": [""],
	"lr": ["sl", "gn", "ci"],
	"ls": ["za"],
	"lt": ["by", "ru", "pl", "lv"],
	"lu": ["be", "de", "fr"],
	"lv": ["ee", "by", "ru", "lt"],
	"ly": ["dz", "ne", "td", "eg", "sd", "tn"],
	"ma": ["dz", "es"],
	"mc": ["fr"],
	"md": ["ua", "ro"],
	"me": ["al", "ba", "hr", "rs"],
	"mg": [""],
	"mh": [""],
	"mk": ["al", "gr", "rs", "bg"],
	"ml": ["bf", "mr", "dz", "ne", "sn", "gn", "ci"],
	"mm": ["bd", "in", "la", "cn", "th"],
	"mn": ["ru", "cn"],
	"mr": ["sn", "dz", "ml"],
	"mt": [""],
	"mu": [""],
	"mv": [""],
	"mw": ["zm", "tz", "mz"],
	"mx": ["us", "gt", "bz"],
	"my": ["bn", "th", "id"],
	"mz": ["sz", "zm", "tz", "za", "zw", "mw"],
	"na": ["bw", "zm", "za", "ao"],
	"ne": ["ml", "bf", "dz", "bj", "td", "ly", "ng"],
	"ng": ["td", "cm", "ne", "bj"],
	"ni": ["hn", "cr"],
	"nl": ["be", "de"],
	"no": ["fi", "ru", "se"],
	"np": ["in", "cn"],
	"nr": [""],
	"nz": [""],
	"om": ["sa", "ye", "ae"],
	"pa": ["cr", "co"],
	"pe": ["ec", "co", "cl", "bo", "br"],
	"pg": ["id"],
	"ph": [""],
	"pk": ["in", "ir", "af", "cn"],
	"pl": ["lt", "by", "ru", "sk", "cz", "ua", "de"],
	"pt": ["es"],
	"pw": [""],
	"py": ["ar", "br", "bo"],
	"qa": ["sa"],
	"ro": ["rs", "bg", "md", "hu", "ua"],
	"rs": ["me", "bg", "ba", "al", "hu", "hr", "mk", "ro"],
	"ru": ["pl", "ge", "kp", "lt", "fi", "by", "mn", "ee", "az", "cn", "no", "ua", "kz", "lv"],
	"rw": ["ug", "bi", "cd", "tz"],
	"sa": ["jo", "om", "iq", "kw", "ae", "qa", "ye"],
	"sb": [""],
	"sc": [""],
	"sd": ["et", "td", "ly", "eg", "ss", "cf", "er"],
	"se": ["fi", "no"],
	"sg": [""],
	"si": ["it", "at", "hr", "hu"],
	"sk": ["pl", "at", "hu", "cz", "ua"],
	"sl": ["lr", "gn"],
	"sm": ["it"],
	"sn": ["ml", "gm", "mr", "gw", "gn"],
	"so": ["ke", "et", "dj"],
	"sr": ["gy", "br"],
	"ss": ["et", "ke", "cf", "ug", "sd", "cd"],
	"st": [""],
	"sv": ["hn", "gt"],
	"sy": ["lb", "tr", "jo", "iq", "il"],
	"sz": ["za", "mz"],
	"td": ["ne", "ly", "cm", "cf", "sd", "ng"],
	"tg": ["gh", "bf", "bj"],
	"th": ["kh", "mm", "la", "my"],
	"tj": ["kg", "uz", "af", "cn"],
	"tl": ["id"],
	"tm": ["kz", "uz", "af", "ir"],
	"tn": ["dz", "ly"],
	"to": [""],
	"tr": ["ge", "bg", "iq", "am", "az", "gr", "sy", "ir"],
	"tt": [""],
	"tv": [""],
	"tz": ["bi", "zm", "rw", "mw", "ke", "ug", "cd", "mz"],
	"ua": ["pl", "by", "ru", "sk", "md", "hu", "ro"],
	"ug": ["tz", "rw", "ke", "ss", "cd"],
	"us": ["mx", "ca"],
	"uy": ["ar", "br"],
	"uz": ["af", "kg", "tm", "tj", "kz"],
	"vc": [""],
	"ve": ["gy", "co", "br"],
	"vn": ["kh", "la", "cn"],
	"vu": [""],
	"ws": [""],
	"ye": ["om", "sa"],
	"za": ["sz", "bw", "zw", "na", "ls", "mz"],
	"zm": ["bw", "ao", "tz", "zw", "mw", "na", "cd", "mz"],
	"zw": ["zm", "za", "bw", "mz"],
};