// NOTE: FIX BRAZIL, ETC WITH NO BORDER THEN DELETE THIS COMMENT

export default {
	"ad": ["es", "fr"],
	"ae": ["sa", "om"],
	"af": ["tm", "cn", "tj", "pk", "ir", "uz"],
	"ag": [""],
	"al": ["mk", "me", "gr", "rs"],
	"am": ["az", "tr", "ir", "ge"],
	"ao": ["cd", "zm", "na", "cg"],
	"ar": ["cl", "uy", "py", "bo", "br"],
	"at": ["sk", "si", "hu", "li", "de", "ch", "cz", "it"],
	"au": [""],
	"az": ["tr", "ru", "am", "ir", "ge"],
	"ba": ["me", "hr", "rs"],
	"bb": [""],
	"bd": ["mm", "in"],
	"be": ["de", "fr", "nl", "lu"],
	"bf": ["tg", "gh", "ml", "ne", "ci", "bj"],
	"bg": ["gr", "tr", "rs", "mk", "ro"],
	"bh": [""],
	"bi": ["tz", "cd", "rw"],
	"bj": ["bf", "tg", "ne", "ng"],
	"bn": ["my"],
	"bo": ["br", "cl", "ar", "py", "pe"],
	"br": ["", "ar", "gy", "uy", "py", "ve", "bo", "pe", "co", "sr"],
	"bs": [""],
	"bt": ["cn", "in"],
	"bw": ["za", "zm", "na", "zw"],
	"by": ["lv", "ua", "lt", "ru", "pl"],
	"bz": ["gt", "mx"],
	"ca": ["us"],
	"cd": ["ug", "zm", "bi", "cf", "cg", "rw", "ao", "tz", "ss"],
	"cf": ["sd", "cg", "td", "cm", "cd", "ss"],
	"cg": ["cf", "ga", "cm", "cd", "ao"],
	"ch": ["at", "li", "de", "fr", "it"],
	"ci": ["gh", "gn", "lr", "bf", "ml"],
	"cl": ["ar", "bo", "pe"],
	"cm": ["cg", "ng", "gq", "ga", "td", "cf"],
	"cn": ["", "vn", "bt", "np", "tj", "pk", "af", "mm", "kp", "in", "ru", "la", "mn", "kg", "kz"],
	"co": ["br", "ve", "pa", "pe", "ec"],
	"cr": ["ni", "pa"],
	"cu": [""],
	"cv": [""],
	"cy": [""],
	"cz": ["sk", "de", "pl", "at"],
	"de": ["at", "lu", "be", "fr", "nl", "ch", "pl", "cz", "dk"],
	"dj": ["er", "so", "et"],
	"dk": ["de"],
	"dm": [""],
	"do": ["ht"],
	"dz": ["ma", "", "tn", "mr", "ml", "ne", "ly"],
	"ec": ["co", "pe"],
	"ee": ["ru", "lv"],
	"eg": ["", "sd", "ly", "il"],
	"er": ["sd", "et", "dj"],
	"es": ["", "ma", "fr", "ad", "pt"],
	"et": ["so", "dj", "sd", "er", "ke", "ss"],
	"fi": ["no", "ru", "se"],
	"fj": [""],
	"fm": [""],
	"fr": ["es", "lu", "de", "be", "ad", "mc", "ch", "it"],
	"ga": ["gq", "cm", "cg"],
	"gb": ["ie"],
	"gd": [""],
	"ge": ["az", "tr", "ru", "am"],
	"gh": ["bf", "tg", "ci"],
	"gm": ["sn"],
	"gn": ["gw", "lr", "sn", "sl", "ml", "ci"],
	"gq": ["cm", "ga"],
	"gr": ["mk", "tr", "al", "bg"],
	"gt": ["hn", "bz", "mx", "sv"],
	"gw": ["gn", "sn"],
	"gy": ["sr", "ve", "br"],
	"hn": ["ni", "gt", "sv"],
	"hr": ["si", "hu", "ba", "me", "rs"],
	"ht": ["do"],
	"hu": ["sk", "si", "at", "ua", "hr", "rs", "ro"],
	"id": ["pg", "my", "tl"],
	"ie": ["gb"],
	"il": ["", "jo", "lb", "eg", "sy"],
	"in": ["bt", "np", "cn", "bd", "pk", "mm"],
	"iq": ["tr", "jo", "kw", "sa", "ir", "sy"],
	"ir": ["tm", "az", "tr", "pk", "iq", "af", "am"],
	"is": [""],
	"it": ["", "si", "at", "fr", "ch", "sm"],
	"jm": [""],
	"jo": ["", "il", "iq", "sa", "sy"],
	"jp": [""],
	"ke": ["ss", "so", "et", "tz", "ug"],
	"kg": ["uz", "cn", "tj", "kz"],
	"kh": ["th", "vn", "la"],
	"ki": [""],
	"km": [""],
	"kn": [""],
	"kp": ["cn", "ru", "kr"],
	"kr": ["kp"],
	"kw": ["iq", "sa"],
	"kz": ["tm", "cn", "ru", "uz", "kg"],
	"la": ["th", "vn", "cn", "kh", "mm"],
	"lb": ["sy", "il"],
	"lc": [""],
	"li": ["at", "ch"],
	"lk": [""],
	"lr": ["gn", "sl", "ci"],
	"ls": ["za"],
	"lt": ["ru", "by", "pl", "lv"],
	"lu": ["de", "be", "fr"],
	"lv": ["lt", "ee", "by", "ru"],
	"ly": ["tn", "sd", "dz", "ne", "td", "eg"],
	"ma": ["", "es", "dz"],
	"mc": ["fr"],
	"md": ["ro", "ua"],
	"me": ["ba", "al", "hr", "rs"],
	"mg": [""],
	"mh": [""],
	"mk": ["al", "bg", "gr", "rs"],
	"ml": ["gn", "mr", "dz", "sn", "bf", "ne", "ci"],
	"mm": ["th", "cn", "bd", "in", "la"],
	"mn": ["cn", "ru"],
	"mr": ["", "ml", "dz", "sn"],
	"mt": [""],
	"mu": [""],
	"mv": [""],
	"mw": ["mz", "zm", "tz"],
	"mx": ["us", "gt", "bz"],
	"my": ["th", "bn", "id"],
	"mz": ["zm", "zw", "sz", "mw", "za", "tz"],
	"na": ["za", "bw", "ao", "zm"],
	"ne": ["dz", "ng", "bf", "ml", "td", "ly", "bj"],
	"ng": ["cm", "td", "ne", "bj"],
	"ni": ["hn", "cr"],
	"nl": ["de", "be"],
	"no": ["ru", "fi", "se"],
	"np": ["cn", "in"],
	"nr": [""],
	"nz": [""],
	"om": ["sa", "ae", "ye"],
	"pa": ["co", "cr"],
	"pe": ["cl", "bo", "br", "co", "ec"],
	"pg": ["id"],
	"ph": [""],
	"pk": ["af", "cn", "in", "ir"],
	"pl": ["sk", "ua", "lt", "de", "by", "ru", "cz"],
	"pt": ["es"],
	"pw": [""],
	"py": ["ar", "bo", "br"],
	"qa": ["sa"],
	"ro": ["hu", "ua", "md", "bg", "rs"],
	"rs": ["al", "hu", "hr", "ba", "bg", "me", "mk", "ro"],
	"ru": ["no", "fi", "lv", "az", "lt", "cn", "by", "ua", "ee", "kp", "pl", "mn", "kz", "ge"],
	"rw": ["tz", "cd", "bi", "ug"],
	"sa": ["jo", "om", "ye", "kw", "iq", "ae", "qa"],
	"sb": [""],
	"sc": [""],
	"sd": ["ly", "er", "et", "td", "eg", "cf", "ss"],
	"se": ["no", "fi"],
	"sg": [""],
	"si": ["it", "hr", "hu", "at"],
	"sk": ["hu", "at", "ua", "pl", "cz"],
	"sl": ["gn", "lr"],
	"sm": ["it"],
	"sn": ["gn", "gw", "mr", "ml", "gm"],
	"so": ["ke", "et", "dj"],
	"sr": ["", "gy", "br"],
	"ss": ["cd", "sd", "et", "ke", "cf", "ug"],
	"st": [""],
	"sv": ["hn", "gt"],
	"sy": ["tr", "jo", "il", "iq", "lb"],
	"sz": ["mz", "za"],
	"td": ["cf", "sd", "ng", "ne", "cm", "ly"],
	"tg": ["gh", "bf", "bj"],
	"th": ["kh", "mm", "my", "la"],
	"tj": ["uz", "af", "cn", "kg"],
	"tl": ["id"],
	"tm": ["uz", "af", "kz", "ir"],
	"tn": ["dz", "ly"],
	"to": [""],
	"tr": ["gr", "az", "iq", "bg", "am", "ir", "sy", "ge"],
	"tt": [""],
	"tv": [""],
	"tz": ["mz", "zm", "bi", "cd", "rw", "mw", "ke", "ug"],
	"ua": ["sk", "hu", "by", "md", "ru", "pl", "ro"],
	"ug": ["cd", "rw", "ke", "tz", "ss"],
	"us": ["ca", "mx"],
	"uy": ["ar", "br"],
	"uz": ["tm", "tj", "af", "kg", "kz"],
	"vc": [""],
	"ve": ["co", "gy", "br"],
	"vn": ["kh", "cn", "la"],
	"vu": [""],
	"ws": [""],
	"ye": ["sa", "om"],
	"za": ["mz", "ls", "zw", "sz", "bw", "na"],
	"zm": ["mz", "na", "zw", "bw", "mw", "cd", "ao", "tz"],
	"zw": ["zm", "mz", "bw", "za"],
};